version: '3.7'
services:
  smart-vote:
    build: .
    command: uvicorn main:app --reload
    volumes:
      - .:/app/
    ports:
      - 8000:8000
  smart-vote-db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=smart-vote
      - POSTGRES_PASSWORD=smart-vote
      - POSTGRES_DB=smart-vote_dev
    ports:
      - 5432:5432

volumes:
  postgres_data: